apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin-app
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc

  project: root-app

  source:
#    repoURL: https://github.com/vanny96/tyk-gateway-setup
    repoURL: git://host.minikube.internal/
    path: root-project/apps/httpbin
    targetRevision: HEAD

  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true