apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: root-app
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: 1.15.0
    chart: cert-manager
    helm:
      values: |
        crds:
          enabled: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
