apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: root-app
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  source:
    repoURL: 'https://helm.tyk.io/public/helm/charts/'
    targetRevision: 0.1.1
    chart: simple-redis
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true