apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: root-app

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 5.2.0
    chart: argo-cd
    helm:
      values: |
        crds:
          install: true
        server:
          extraArgs:
            - "--disable-auth"
            - "--insecure"
          ingress:
            enabled: "true"
            hosts:
              - argocd.local
            annotations:
              # kubernetes.io/ingress.class: ambassador ### For some ingress controllers required
        dex:
          enabled: "false"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true