apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc

  project: root-app

  source:
    repoURL: https://github.com/vanny96/tyk-gateway-setup
    path: root-project/infra
    targetRevision: HEAD