apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Test project to delete

  sourceRepos:
    - '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  destinations:
    - namespace: '*'
      server: '*'